version: '2.1'

services:

  api:
    restart: always
    build:
      context: .
    ports:
      - "5000:5000"
    volumes:
      - ./src:/usr/src
    working_dir: /usr/src
    env_file: .env
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 5000

  console:
    restart: always
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src
    working_dir: /usr/src
    env_file: .env
    command: uvicorn console.main:app --reload --host 0.0.0.0 --port 8000
